name: CI

on:
  push:
    branches: [Jesse, Ning, Moustafa]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          pip install fastapi tensorflow numpy pillow

      - name: Vérifier que le code compile
        run: |
          find . -name "*.py" -not -path "./.github/*" -exec python -m py_compile {} \;
